### ISSUE TITLE
Adding RGB-D cameras to robot model

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_morse#1]
Our robot model needs at least one RGB-D camera. It could be in a fixed position to start, but ideally on a PTU.

**Comment by kunzel** [comment]
Agreed :) Today I was trying to get a depth camera, ie kinect, working on our robot model. It turned out that using a depth camera in MORSE requires Python 3.3 and a corresponding Blender version (2.65a). After trying different versions I finally managed to get it running. Details will follow shortly.

**Comment by kunzel** [comment]
A depth camera (PointCloud2) and videoCamera (Image) are on a PTU on the robot used in the TUM kitchen (default-with-kinect.py). I think it's not very handy to add them to every new environment every time manually to the robot. Therefore I would like to put them directly into the robot model. However, this would mean that we have to use Python 3.3 and cannot use the fast_mode of MORSE anymore. Maybe there is also a way to disable the cameras by passing an argument in the Scitos() constructor. However, I would make them enabled by default. Is everybody fine with this?

**Comment by hawesie** [comment]
I'm happy as it's the right thing in general. But this is provided there is a way to turn them off as they segfault my MORSE on OS X!
