### ISSUE TITLE
adding a human doesn't work

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_morse#21]
I tried to add a human to our simulation using `human=Human()` but it fails with the following message

```
[ERROR][MORSE] Your builder script is invalid!
  File "/opt/strands/lib/python3.3/site-packages/morse/blender/human_interaction/human_control.py", line 549, in rotate
    pos =  scene.objects['POS_EMPTY' + suffix]


```

Any idea about that? I checked that there is a POS_EMPTY object in Human.blend, so I don't know what's going wrong. Before I bother the morse people, I thought you might have an idea.

**Comment by marc-hanheide** [comment]
Anyone? Any idea? @hawsie?

**Comment by kunzel** [comment]
@marc-hanheide, the error can be resolved when commenting two lines in the scitos's robot builder file. However, I don't understand the problem yet.
In [scitosA5.py](https://github.com/strands-project/strands_morse/blob/master/strands_sim/src/strands_sim/builder/robots/scitosA5.py) please comment the following two lines:

21 #self.add_interface('ros')
55 #self.odometry.add_interface('ros', topic="/odom")

This bug seems to be related: https://github.com/morse-simulator/morse/issues/257

cheers,
Lars

**Comment by marc-hanheide** [comment]
Cheers! I fixed it the easy way: By updating morse from github ;-) The bug has now been fixed in master. 
I now included a quick guide on how to update Morse (very obvious): https://github.com/strands-project/strands_systems#updating-morse

Thanks for the support,

Marc
