### ISSUE TITLE
/head_xtion/rgb/image_color doesn't stream any images

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_morse#48]
While `/head_xtion/rgb/image_mono` works, `/head_xtion/rgb/image_color` never sends any data...

**Comment by kunzel** [comment]
There is only image topic published by MORSE, which is currently image_mono, which is a little bit odd because it is a color image. I only changed the topic name (color->mono) because @gestom switched the topic name in the visual docking some time ago. But we can also switch it back to color if this is preferable.

**Comment by marc-hanheide** [comment]
A workaround could be to add another camera so we actually have both? Or implement a node that takes the colour image and republishes it as mono?

**Comment by cdondrup** [comment]
Just as a side note: The people detector will need both, the colour and mono image. So it would be great if we could have both available. 
Whether the detection will work in simulation or not is another question...

**Comment by nilsbore** [comment]
This was fixed by adding the openni stack: https://github.com/strands-project/strands_morse/pull/68.
